# Generated by Django 4.1.1 on 2023-01-14 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='academic_year',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 0, 16, 7, 933766)),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_debut',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 0, 16, 7, 932769)),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_fin',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 0, 16, 7, 932769)),
        ),
    ]
