# Generated by Django 4.1.1 on 2023-01-14 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='academic_year',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 0, 26, 19, 705)),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_debut',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 0, 26, 19, 705)),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_fin',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 0, 26, 19, 705)),
        ),
    ]
