# Generated by Django 4.1.1 on 2023-01-15 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email_alter_etudiant_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='academic_year',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 2, 8, 25, 199275)),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_debut',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 2, 8, 25, 198278)),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_fin',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 2, 8, 25, 198278)),
        ),
    ]
